### ISSUE TITLE
Title of Hyper-Twister Roller Coaster is wrong in English (US) & (UK)

### ISSUE THREAD

**Issue by daihakken** [OpenRCT2/Localisation#151]
![hyper](https://cloud.githubusercontent.com/assets/13048125/8510987/941925c0-2335-11e5-9378-a3f6732c7bc9.jpg)
![twist](https://cloud.githubusercontent.com/assets/13048125/8510988/941b4b3e-2335-11e5-80c4-5507889ca06e.jpg)

**Comment by Gymnasiast** [comment]
The problem here is that the Hyper Twister RC uses the generic track name, which really should be 'Twister Roller Coaster', as that's what all steel twister roller coasters use. Changing it to 'Hyper twister' would make the generic name incorrect.

I'll change it to 'Steel Twister RC', to properly differentiate between the two.

**Comment by daihakken** [comment]
But the vanilla game was using "Hyper Twister" for the Hyper Twister RC....

**Comment by Gymnasiast** [comment]
Yes, but this isn't vanilla. Take a look at the object selection in the Scenario Editor for Floorless RC, for example: it's a type of Twister RC, but it isn't a Hyper-Twister (speaking in real-world terms). The same applies if you turn on Selection by track type: it will group rides together under the generic name, which should be (Steel) Twister RC, not Hyper-Twister.

The set-up in vanilla is simply technically incorrect, but that's not visible in vanilla. In OpenRCT2, with its extended functionality, it has become visible.
