### ISSUE TITLE
french version there is a fault in a message

### ISSUE THREAD

**Issue by hatokuro** [OpenRCT2/Localisation#1802]
**OS: Windows 7
**Version: 6.1
**Commit/Build: 7601: Service Pack 1

OpenRCT2-0.2.4-windows-portable-x64
french version fault message Visiteurs.
"J'ai déjà un un ballon"

correct is 

"J'ai déjà un ballon"

it is not only on this message that there is a repetition.

![ort2](https://user-images.githubusercontent.com/35025697/73351956-5c54b300-4290-11ea-9e49-8e813e153cbb.png)

**Comment by AaronVanGeffen** [comment]
This happens because:
https://github.com/OpenRCT2/Localisation/blob/5ec4fa310491050c5fc629f3198bc63f34d04eb2/data/language/fr-FR.txt#L876
and 
https://github.com/OpenRCT2/Localisation/blob/5ec4fa310491050c5fc629f3198bc63f34d04eb2/data/language/fr-FR.txt#L1419
both use the indefinite article 'un'.

@JoelTroch, could you look into this?

**Comment by JoelTroch** [comment]
Will take a look as soon as I can
