### ISSUE TITLE
Translation script should not treat STR_5151 and STR_5152 as technical strings

### ISSUE THREAD

**Issue by marcinkunert** [OpenRCT2/Localisation#2011]
These strings are the thousands and decimal point separators and differ depending on locale

https://github.com/OpenRCT2/OpenRCT2/blob/9dcbf6d4e62bd13cf167b63bab69bfd26c20e10c/src/openrct2/localisation/StringIds.h#L2643-L2644

According to this: https://docs.oracle.com/cd/E19455-01/806-0169/overview-9/index.html

In German a big number would be written like this: 4 294 967.295,000
In English: 4,294,967,295.00
In Italian: 4.294.967.295,000
In Danish/Finnish/French: 4 294 967 295,000  

There is also a large article on that on wikipedia: https://en.wikipedia.org/wiki/Decimal_separator

**Comment by tupaschoal** [comment]
Looks like you're right, I didn't double check if all languages had it equal, but I added the `Unexpected translation` warning so that we can read the log and see how many of those skipped ones shouldn't (because there are differences and there really should be) or really should and there is an "error" in the translation.

**Comment by frenchiveruti** [comment]
What's the "ISO" way of presenting big numbers?
