### ISSUE TITLE
Missing `=` in map window strings for Catalan

### ISSUE THREAD

**Issue by mrmbernardi** [OpenRCT2/Localisation#2767]
These strings are missing the `=` character which is present in the other languages. But perhaps this is deliberate because this language has unusually long strings for the map window?

https://github.com/OpenRCT2/Localisation/blob/ba4475a07513ad34cec4127d1b808407e4d107ef/data/language/ca-ES.txt#L2380-L2387

**Comment by Gymnasiast** [comment]
I generally leave decision like this to the translators themselves, but it doesn’t hurt to notify them.

Tagging @J0anJosep .

**Comment by J0anJosep** [comment]
Hi. I removed the equal signs because they are irrelevant and it is very strange to add an equal sign for labels on a legend of a map.

Moreover, as I try to translate the strings so they sound as natural as possible for the user, usually strings are longer than in English. So, having a little extra space helps, as the widgets of the windows still do not resize themselves depending on the length of the drawn string.

If you think this is an issue that needs to be resolved, I'll add the equal signs myself and will create the corresponding PR. If not, you can close the issue.

Thank you for telling about it!

**Comment by mrmbernardi** [comment]
I wanted to find out if it was an oversight. I think they're fine without the equals signs too.

**Comment by Gymnasiast** [comment]
@J0anJosep You don’t need to add them, I want translations to make sense for the users too. After all, the point is to make the game accessible and give speakers of other language a good experience, not to make a literal translation. This is also why I tend to give the translators a lot of leeway in how they want to approach things.
